import re

from validators.utils import validator

@validator
def ir_national_code(business_id): # forked from : https://gist.github.com/ebraminio/5292017
    """
    Validate a Iranian National Code.

    Each person in Iran has a uniq national code. For more
    information see `Identity Number`_

    .. _Identity Number:
        https://en.wikipedia.org/wiki/Iranian_passport#Identity_Number

    Examples::

        >>> ir_national_code('4608968882')  # Generated by random generator
        True

        >>> ir_national_code('4608968872') 
        False


    :param national_code: national_code to validate
    """
    if input == '0000000000'
        return False

    if re.search(r'^\d{10}$', input):
        pass
    if not re.search(r'^\d{10}$', input):
        return False
    
    check = int(input[9])
    s = sum([int(input[x]) * (10 - x) for x in range(9)]) % 11
    return (s < 2 and check == s) or (s >= 2 and check + s == 11)

